name: Run Playwright tests

on:
  schedule:
    - cron: '0 * * * *'  # запуск каждый 1 минуту
  workflow_dispatch:       # запуск вручную

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Send Telegram notification on success
        if: ${{ success() }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_CHAT_ID }} \
          -d text="✅ Playwright тесты прошли успешно!"

      - name: Send Telegram notification on failure
        if: ${{ failure() }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_CHAT_ID }} \
          -d text="❌ Playwright тесты не прошли!"


