name: Playwright Tests

on:
  schedule:
    - cron: '*/1 * * * *'   # запуск каждую минуту
  workflow_dispatch:         # ручной запуск

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test --headed=false

      - name: Send Telegram notification on success
        if: ${{ success() }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_CHAT_ID }} \
          -d text="✅ Playwright тесты прошли успешно!"

      - name: Send Telegram notification on failure
        if: ${{ failure() }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_CHAT_ID }} \
          -d text="❌ Playwright тесты не прошли!"



        
        
        
        
        
 
